# Generated by Django 5.2.7 on 2025-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
