# Generated by Django 5.2.7 on 2025-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
