# Generated by Django 5.2.7 on 2025-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage_location',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
