# Generated by Django 5.2.7 on 2025-11-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_storage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('component_status', models.CharField(choices=[('ok', 'OK'), ('faulty', 'Faulty'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='ok', max_length=20)),
                ('issuer', models.CharField(choices=[('harsh', 'Harsh'), ('gaurav', 'Gaurav')], max_length=20)),
                ('issue_condition', models.CharField(choices=[('returnable', 'Returnable'), ('non_returnable', 'Non-returnable')], default='returnable', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('received', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='inventory.item')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
