# Generated by Django 5.2.7 on 2025-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_is_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storage_location',
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_no',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
