# Generated by Django 5.2.7 on 2026-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_item_storage_location_alter_item_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='component_status',
            field=models.CharField(choices=[('ok', 'OK'), ('faulty', 'Faulty'), ('lost', 'Lost')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issue_condition',
            field=models.CharField(choices=[('returnable', 'Returnable'), ('non_returnable', 'Non-Returnable')], default='returnable', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issuer',
            field=models.CharField(choices=[('Harsh', 'Harsh'), ('Gaurav', 'Gaurav')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_no',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
